/**
 * Applied output — src/pages/Home.tsx for Latch (SaaS code-review tool).
 *
 * Generated by the master prompt against the Latch brief. Drop into
 * src/pages/Home.tsx replacing the placeholder version.
 */
import { Bug, Shield, Zap, GitBranch, Lock, Clock, Cpu, Users } from 'lucide-react';
import { JsonLd } from '@/components/JsonLd';
import { useSEO } from '@/hooks/useSEO';
import { brand, featureOn } from '@/brand';
import { buildSiteJsonLd } from '@/lib/businessSchema';

import {
  HeroCenter,
  LogoCloud,
  BentoGrid,
  Stats,
  FeatureSplit,
  Pricing,
  FAQ,
  CaseStudyGrid,
  CTASection,
  Newsletter,
  type BentoTile,
  type Stat,
  type PricingTier,
  type FAQItem,
  type Logo,
  type CaseStudy,
} from '@/components/sections';

const features: BentoTile[] = [
  { id: 'bugs',     title: 'Catches what humans miss',         description: 'Race conditions, off-by-ones, regex DoS, unsafe SQL, missing null checks. Trained on 50M open-source PRs.', icon: <Bug size={24} />,      span: 'lg', tall: true, accent: true },
  { id: 'speed',    title: 'Runs in 47 seconds',               description: 'Median PR review time. Faster than your CI tests.',                                                          icon: <Zap size={24} />,      span: 'sm' },
  { id: 'languages',title: '14 languages supported',            description: 'TypeScript, Python, Go, Rust, Java, Kotlin, Swift, Ruby, PHP, C++, C#, Elixir, Scala, Bash.',               icon: <Cpu size={24} />,      span: 'sm' },
  { id: 'github',   title: 'Drops into existing CI',           description: 'GitHub App. Two clicks to install. Configure once in `.latch.yml`.',                                          icon: <GitBranch size={24} />,span: 'md' },
  { id: 'security', title: 'SOC 2 Type II + GDPR',             description: 'Audit log retention 7 years on Enterprise. Self-hosted option for regulated industries.',                    icon: <Lock size={24} />,     span: 'md' },
];

const stats: Stat[] = [
  { value: 50_000_000, suffix: '+', label: 'PRs in training set' },
  { value: 12_000,     suffix: '+', label: 'Teams using Latch' },
  { value: 47,         suffix: 's', label: 'Median review time' },
  { value: 99,         suffix: '.99%', label: 'Uptime SLA' },
];

const logos: Logo[] = [
  { name: 'Acme' },        { name: 'Globex' },     { name: 'Initech' },
  { name: 'Wonka' },       { name: 'Stark' },      { name: 'Cyberdyne' },
];

const tiers: PricingTier[] = [
  {
    id: 'free',
    name: 'Free',
    description: 'Solo developers + public repos.',
    monthly: 0,
    yearly: 0,
    features: [
      'Up to 5 PRs / month',
      '1 user',
      'All AI checks',
      'Public repos only',
      'Community support (Discord)',
    ],
    cta: { label: 'Install on GitHub', href: 'https://github.com/apps/latch' },
  },
  {
    id: 'team',
    name: 'Team',
    description: 'Engineering teams 2-50.',
    monthly: 19,
    yearly: 182,
    featured: true,
    badge: 'Most popular',
    features: [
      'Unlimited PRs',
      'Up to 50 users',
      'All AI checks',
      'Public + private repos',
      'Custom rules in `.latch.yml`',
      'SAML SSO',
      'SOC 2 attestation on request',
      'Email + Slack support',
    ],
    cta: { label: 'Start free trial', href: '/contact?intent=trial' },
  },
  {
    id: 'enterprise',
    name: 'Enterprise',
    description: 'Regulated industries + 50+ engineers.',
    monthly: 499,
    yearly: 4790,
    features: [
      'Unlimited PRs + users',
      'Self-hosted option (Helm chart)',
      'SCIM provisioning',
      'Custom data retention',
      'Audit log retention 7 years',
      'Dedicated CSM',
      'Custom SLA + uptime credits',
      'Security review with your team',
    ],
    cta: { label: 'Talk to sales', href: '/contact?intent=enterprise' },
  },
];

const caseStudies: CaseStudy[] = [
  {
    slug: 'acme-deploy-velocity',
    title: 'Acme — 3× deploy velocity, half the rollbacks',
    client: 'Acme Inc.',
    industry: 'B2B SaaS · 220 engineers',
    summary: 'Cut PR review time from 6.2 hours median to 38 minutes. Production rollbacks dropped from 14/month to 7. Same engineering headcount.',
    cover: '/case/acme.jpg',
    metrics: [
      { value: '3×',  label: 'Deploys / week' },
      { value: '−50%', label: 'Rollbacks' },
      { value: '38m', label: 'PR review time' },
    ],
  },
  {
    slug: 'cyberdyne-zero-day-prevention',
    title: 'Cyberdyne — Caught a zero-day before staging',
    client: 'Cyberdyne Systems',
    industry: 'Industrial software · 80 engineers',
    summary: 'Latch flagged a regex-DoS vulnerability in a PR that had two human approvals. Saved a P0 in production.',
    cover: '/case/cyberdyne.jpg',
    metrics: [
      { value: '1',   label: 'P0 prevented' },
      { value: '$240K', label: 'Estimated saved' },
      { value: '<1s', label: 'Detection time' },
    ],
  },
];

const faqs: FAQItem[] = [
  {
    question: 'How does Latch work?',
    answer: 'Latch installs as a GitHub App. When you open a pull request, Latch reads the diff plus relevant context (changed files, related tests, recent history) and posts inline comments on lines it flags. Average review takes 47 seconds. You see suggestions; you decide what to ship.',
  },
  {
    question: 'What languages do you support?',
    answer: 'TypeScript, JavaScript, Python, Go, Rust, Java, Kotlin, Swift, Ruby, PHP, C++, C#, Elixir, Scala, and Bash. We add languages based on training data availability — request via hello@latch.example.',
  },
  {
    question: 'Will Latch slow down our CI?',
    answer: 'No. Latch runs out-of-band on our infrastructure, not in your CI runners. Comments appear on the PR within 47 seconds median (p99 under 3 minutes). Your CI is untouched.',
  },
  {
    question: 'Where is my code stored?',
    answer: 'Diffs are processed in-memory and discarded immediately after review on Free and Team plans. Enterprise customers can configure retention from 0 days to 7 years. EU customers can pin to our eu-west-1 region.',
  },
  {
    question: 'Can I self-host Latch?',
    answer: 'Yes — Enterprise customers get a Helm chart that runs Latch in your own Kubernetes cluster. Your code never leaves your network. Talk to sales for installation support.',
  },
  {
    question: 'How is this different from CodeRabbit / Greptile / Cursor?',
    answer: 'CodeRabbit and Greptile focus on summarization. Cursor focuses on writing code. Latch focuses on the bugs other reviewers (human and AI) miss — race conditions, regex DoS, SQL injection, missing null checks. We post fewer comments, but the ones we post matter.',
  },
  {
    question: 'Do you offer a SOC 2 report I can share?',
    answer: 'Yes. Team customers can request our SOC 2 Type II attestation via email. Enterprise customers get the full report under NDA, plus our security review on request.',
  },
  {
    question: 'Can I cancel anytime?',
    answer: 'Yes. Cancel from your billing page; access continues through the end of the billing period. We refund unused months on annual plans, no questions asked.',
  },
];

export default function Home() {
  useSEO({
    title: 'Latch — AI code review that catches what humans miss',
    description: brand.business.description,
  });

  return (
    <>
      <JsonLd data={buildSiteJsonLd({
        name: brand.business.name,
        description: brand.business.description,
        url: brand.business.url,
        businessClass: 'saas',
        email: brand.business.email,
        sameAs: [
          'https://github.com/uselatch',
          'https://twitter.com/uselatch',
          'https://linkedin.com/company/latch',
        ],
      })} />

      <JsonLd
        data={{
          '@context': 'https://schema.org',
          '@type': 'SoftwareApplication',
          name: brand.business.name,
          applicationCategory: 'DeveloperApplication',
          operatingSystem: 'Web',
          offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
          aggregateRating: {
            '@type': 'AggregateRating',
            ratingValue: '4.8',
            reviewCount: '412',
            bestRating: '5',
          },
        }}
      />

      {featureOn('hero') && (
        <HeroCenter
          eyebrow="Built for engineering teams"
          headline="Every PR. Reviewed twice."
          subheadline="Latch reads every pull request against 50M open-source repos. Flags race conditions, regex DoS, unsafe SQL — bugs review misses."
          primary={{ label: 'Install on GitHub', href: 'https://github.com/apps/latch' }}
          secondary={{ label: 'See pricing', href: '/pricing' }}
          trustBadges={[
            { icon: 'star',   label: '12,000 teams · 47 countries' },
            { icon: 'shield', label: 'SOC 2 Type II · GDPR ready' },
            { icon: 'award',  label: 'Cloudflare · 99.99% uptime' },
          ]}
        />
      )}

      {featureOn('logoCloud') && (
        <LogoCloud eyebrow="Trusted by engineering teams at" logos={logos} variant="marquee" />
      )}

      {featureOn('bento') && (
        <BentoGrid
          eyebrow="What we catch"
          headline="The bugs your review process misses"
          description="Built on 50M open-source PRs across 14 languages. Trained specifically on the bug classes that escape human reviewers — and the AI reviewers that summarize instead of catch."
          tiles={features}
        />
      )}

      {featureOn('stats') && (
        <Stats
          eyebrow="By the numbers"
          stats={stats}
        />
      )}

      <FeatureSplit
        eyebrow="How it works"
        headline="Install in 60 seconds. First review in under a minute."
        description="Authorize the GitHub App. Configure once in .latch.yml (optional). Open a PR. Latch posts inline comments within 47 seconds median."
        bullets={[
          'GitHub App (GitLab + Bitbucket in beta)',
          'Custom rules in `.latch.yml`',
          'Slack notifications + dashboards',
          'CLI for local dev (`latch review`)',
        ]}
        cta={{ label: 'Read the install docs', href: '/docs/install' }}
        image={{ src: '/screenshot-pr.png', alt: 'Latch posting inline comments on a GitHub pull request with three suggestions and one warning' }}
      />

      {featureOn('caseStudies') && (
        <CaseStudyGrid
          eyebrow="Case studies"
          headline="What teams shipped after switching"
          studies={caseStudies}
        />
      )}

      {featureOn('pricing') && (
        <Pricing
          eyebrow="Pricing"
          headline="Free for solo devs. $19 / seat for teams."
          description="No setup fees. No per-PR charges. Cancel anytime."
          tiers={tiers}
        />
      )}

      {featureOn('faq') && (
        <FAQ
          eyebrow="Questions"
          headline="Frequently asked"
          items={faqs}
        />
      )}

      {featureOn('newsletter') && (
        <Newsletter
          badge="Free · Weekly"
          headline="Get the changelog"
          description="One email a week. New checks, language support, bug fixes. No marketing emails — that's a separate signup."
        />
      )}

      {featureOn('cta') && (
        <CTASection
          eyebrow="Ready?"
          headline="Install Latch in 60 seconds."
          description="Free up to 5 PRs / month. No card required. Upgrade when you need more."
          primary={{ label: 'Install on GitHub', href: 'https://github.com/apps/latch' }}
          secondary={{ label: 'Talk to sales', href: '/contact?intent=enterprise' }}
          tone="emphatic"
        />
      )}
    </>
  );
}
